### ISSUE TITLE
I feel fba aspect ratio 8.57 is wrong

### ISSUE THREAD

**Issue by juzt3** [cjuniorfox/retropie-crt#3]
as the title says with that config some parte of the image is out of view. this does happend with the rest of games i play. i mean snes and the rest

**Comment by cjuniorfox** [comment]
It isn´t straightforward, because FBA, like MAME, it's a multi-platform emulator. So, it´s hard to pick up some platforms and do a proper configuration because what is right for some platforms is wrong for others.
So, I picked up a general value that ranges from some generic resolutions, like 320, 640 and 256 and make it render closest as should be.

But, feel free to make some addition. Change the aspect ratio value and find whats makes more sense. I do some testing and add it as default.

**Comment by juzt3** [comment]
I have made my own version using crtpi and your work too and now i have the correct resolution per game https://github.com/juzt3/CRTPi-HDMI2YPbPr please take a look and tell me if you're ok with it becose i took things from your work

**Comment by cjuniorfox** [comment]
Great. But it's a lot of work.
There's a way to get the resolution from the core itself. I working on it

**Comment by cjuniorfox** [comment]
Fixed. Now, with the new script [chvideocore.py](https://github.com/cjuniorfox/retropie-crt/blob/develop/resources/opt/retropie-crt/scripts/chvideocore.py), the [chvideo.py](https://github.com/cjuniorfox/retropie-crt/blob/develop/resources/opt/retropie-crt/scripts/chvideo.py) can configure the exact resolution for the Arcade game.

The only downside is about the 50Hz and 60Hz set (PAL/NTSC). Because some games were developed with one system or another in mind, the video mode is set accordingly with the game independent of the original intended configuration.

**Comment by cjuniorfox** [comment]
Fixed on this commit
d9ee68ebe3a306ac240a02bdff4651c05874bac5
